spring.application.name=backen-ai
openrouter.api-key=${OPENROUTER_API_KEY}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB

app.jwt.secret=demo-ai-super-secret-key-demo-ai-super-secret-key-123456
app.jwt.expiration-ms=86400000