spring.application.name=backen-ai
openrouter.api-key=${OPENROUTER_API_KEY}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-form-post-size=200MB
server.tomcat.max-swallow-size=200MB

app.jwt.secret=demo-ai-super-secret-key-demo-ai-super-secret-key-123456
app.jwt.expiration-ms=86400000

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:tiktok_ai}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.admin.username=admin
app.admin.password=123456
app.admin.full-name=System Administrator
app.admin.email=admin@demo-ai.com

app.purchase.video10.extra-videos=10
app.purchase.video10.amount=29000
app.purchase.bank.bin=970422
app.purchase.bank.account-no=0336837590
app.purchase.bank.account-name=DO TRONG HAI

app.admin.review-url=${FRONTEND_URL:http://localhost:5173}/admin/purchases
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vipboy97lol@gmail.com
spring.mail.password=neqpxzbyzvxsvwoq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true